/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#0c0e11",
        "on-error": "#690005",
        "error": "#ffb4ab",
        "on-surface": "#e2e2e6",
        "on-secondary": "#2f3130",
        "on-secondary-fixed-variant": "#454746",
        "tertiary-container": "#001750",
        "on-tertiary-fixed-variant": "#003cae",
        "primary-container": "#1a1d21",
        "on-primary": "#2e3135",
        "on-primary-fixed": "#191c20",
        "on-tertiary-fixed": "#00164e",
        "primary": "#c5c6cc",
        "on-secondary-container": "#b4b5b4",
        "inverse-primary": "#5c5e63",
        "surface-container-low": "#1a1c1f",
        "surface-container-high": "#282a2d",
        "background": "#111316",
        "on-tertiary": "#00287c",
        "surface-variant": "#333538",
        "surface-container": "#1e2023",
        "inverse-surface": "#e2e2e6",
        "secondary-container": "#454746",
        "surface-bright": "#37393d",
        "inverse-on-surface": "#2f3034",
        "primary-fixed": "#e1e2e8",
        "secondary-fixed-dim": "#c6c7c5",
        "primary-fixed-dim": "#c5c6cc",
        "surface-tint": "#c5c6cc",
        "surface": "#111316",
        "outline-variant": "#45474a",
        "on-tertiary-container": "#507cff",
        "tertiary": "#b5c4ff",
        "tertiary-fixed": "#dce1ff",
        "surface-container-highest": "#333538",
        "on-primary-container": "#82858a",
        "on-primary-fixed-variant": "#44474b",
        "outline": "#8f9195",
        "tertiary-fixed-dim": "#b5c4ff",
        "secondary-fixed": "#e2e3e1",
        "on-error-container": "#ffdad6",
        "secondary": "#c6c7c5",
        "surface-dim": "#111316",
        "error-container": "#93000a",
        "on-secondary-fixed": "#1a1c1b",
        "on-background": "#e2e2e6",
        "on-surface-variant": "#c5c6ca"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "base": "8px",
        "section-gap": "5rem",
        "gutter": "1.5rem",
        "container-padding-mobile": "1.25rem",
        "container-padding-desktop": "2.5rem"
      },
      fontFamily: {
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["64px", { "lineHeight": "72px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-lg": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "headline-lg-mobile": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
